import Layout from "../components/Layout";
import About from "../components/About.jsx";
import Head from "next/head";
import favicon from "./favicon.ico"
export default function about()
{
    return(
        <Layout>
            <Head>
          <title>Handcrafted Haven</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" type="image/x-icon" href={favicon.src} />
        </Head>
            <About/>
        </Layout>
    )
}